Book-Rental-MVC/Controllers/KiralamaController.cs
using Book_Rental_MVC.Models;
using Book_Rental_MVC.Models.Abstract;
using Book_Rental_MVC.Models.Concrete;
using Book_Rental_MVC.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;

namespace Book_Rental_MVC.Controllers
{
    [Authorize(Roles = UserRoles.Role_Admin)]
    public class KiralamaController : Controller
    { 
        private readonly IKiralamaRepository _repository;
        private readonly IKitapRepository _kitapRepository;
        public readonly IWebHostEnvironment _webHostEnvironment;
        public KiralamaController(IKiralamaRepository kiralamaRepository, IKitapRepository kitapRepository, IWebHostEnvironment webHostEnvironment)
        {
            _repository = kiralamaRepository;
            _kitapRepository = kitapRepository; 
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            List<Kiralama> kiralamaList = _repository.GetAll(includeProps:"Kitap").ToList();
            return View(kiralamaList);
        }

        public IActionResult EkleGuncelle(int? id)
        {
            IEnumerable<SelectListItem> KitapList = _kitapRepository.GetAll()
                .Select(k => new SelectListItem { Text = k.KitapAdi, Value = k.Id.ToString() });

            ViewBag.KitapList = KitapList;

            if (id == null || id == 0)
                return View();
            else
            {
                Kiralama? kiralamaVt = _repository.Get(i => i.Id == id); // idye ait kaydi getir

                if (kiralamaVt == null)
                    return NotFound();

                return View(kiralamaVt);
            }
        }

        [HttpPost]
        public IActionResult EkleGuncelle(Kiralama model)
        {
            if(ModelState.IsValid) 
            {
                if (model.Id == 0)
                {
                    _repository.Ekle(model);
                    TempData["SuccessMessage"] = "Yeni Kiralama Kaydı Oluşturuldu";
                }
                else
                {
                    _repository.Guncelle(model);
                    TempData["SuccessMessage"] = "Yeni Güncelleme Başarılı";
                }
                _repository.Kaydet();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Sil(int? id)
        {
            IEnumerable<SelectListItem> KitapList = _kitapRepository.GetAll()
                .Select(k => new SelectListItem { Text = k.KitapAdi, Value = k.Id.ToString() });

            ViewBag.KitapList = KitapList;

            if (id == null || id == 0)
                return NotFound();

            Kiralama? kiralamaVt = _repository.Get(i => i.Id == id); // idye ait kaydi getir

            if (kiralamaVt == null)
                return NotFound();

            return View(kiralamaVt);
        }

        [HttpPost, ActionName("Sil")]
        public IActionResult SilPost(int? id)
        {
            Kiralama? kiralama = _repository.Get(i => i.Id == id);

            if (kiralama == null)
            {
                TempData["ErrorMessage"] = "Silmek istediğiniz kayıt bulunamadı!";
                return NotFound();
            }

            _repository.Sil(kiralama);
            _repository.Kaydet();
            TempData["SuccessMessage"] = "Kiralama kaydı başarıyla silindi!";

            return RedirectToAction("Index");
        }
    }
}

Book-Rental-MVC/Controllers/KitapController.cs
using Book_Rental_MVC.Models;
using Book_Rental_MVC.Models.Abstract;
using Book_Rental_MVC.Models.Concrete;
using Book_Rental_MVC.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;

namespace Book_Rental_MVC.Controllers
{
    public class KitapController : Controller
    {
        private readonly IKitapRepository _repository;
        private readonly IKitapTuruRepository _kitapTuruRepository;
        public readonly IWebHostEnvironment _webHostEnvironment;
        public KitapController(IKitapRepository kitapRepository, IKitapTuruRepository kitapTuruRepository, IWebHostEnvironment webHostEnvironment)
        {
            _repository = kitapRepository;
            _kitapTuruRepository = kitapTuruRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        [Authorize(Roles = "Admin,Ogrenci")]
        public IActionResult Index()
        {
            List<Kitap> kitapList = _repository.GetAll(includeProps:"KitapTuru").ToList();
            return View(kitapList);
        }

        [Authorize(Roles = UserRoles.Role_Admin)]
        public IActionResult EkleGuncelle(int? id)
        {
            IEnumerable<SelectListItem> KitapTuruList = _kitapTuruRepository.GetAll()
                .Select(k => new SelectListItem { Text = k.Ad, Value = k.Id.ToString() });

            ViewBag.KitapTuruList = KitapTuruList;

            if (id == null || id == 0)
                return View();
            else
                return ContextBulVeDon(id);
        }

        [Authorize(Roles = UserRoles.Role_Admin)]
        [HttpPost]
        public IActionResult EkleGuncelle(Kitap model, IFormFile? file)
        {
            if(ModelState.IsValid) 
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                string kitapPath = Path.Combine(wwwRootPath, @"img");

                if (file != null)
                {
                    using (var fileStream = new FileStream(Path.Combine(kitapPath, file.FileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    model.ResimUrl = @"\img\" + file.FileName;
                }
              
                if (model.Id == 0)
                {
                    _repository.Ekle(model);
                    TempData["SuccessMessage"] = "Yeni Kitap Oluşturuldu";
                }
                else
                {
                    _repository.Guncelle(model);
                    TempData["SuccessMessage"] = "Yeni Güncelleme Başarılı";
                }
                _repository.Kaydet();
                return RedirectToAction("Index");
            }
            return View();
        }

        [Authorize(Roles = UserRoles.Role_Admin)]
        public IActionResult Sil(int? id)
        {
            return ContextBulVeDon(id);
        }

        [Authorize(Roles = UserRoles.Role_Admin)]
        [HttpPost, ActionName("Sil")]
        public IActionResult SilPost(int? id)
        {
            Kitap? kitap = _repository.Get(i => i.Id == id);

            if (kitap == null)
            {
                TempData["ErrorMessage"] = "Silmek istediğiniz kayıt bulunamadı!";
                return NotFound();
            }

            _repository.Sil(kitap);
            _repository.Kaydet();
            TempData["SuccessMessage"] = "Kitap başarıyla silindi!";

            return RedirectToAction("Index");
        }

        private IActionResult ContextBulVeDon(int? id)
        {
            if (id == null)
                return NotFound();

            Kitap? kitapVt = _repository.Get(i => i.Id == id); // idye ait kaydi getir

            if (kitapVt == null)
                return NotFound();

            return View(kitapVt);
        }
    }
}

Book-Rental-MVC/Views/Shared/_Layout.cshtml
@using Book_Rental_MVC.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Book_Rental_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Book_Rental_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Online Kütüphane</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">İletişim</a>
                        </li>
                        @if(User.IsInRole(UserRoles.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="KitapTuru" asp-action="Index">Kitap Türü</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Kitap" asp-action="Index">Kitap İşlemleri</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Kiralama" asp-action="Index">Kiralama İşlemi</a>
                            </li>
                        }
                        @if (User.IsInRole(UserRoles.Role_Ogrenci))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Kitap" asp-action="Index">Kitap Listesi</a>
                            </li>
                        }

                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Anıl Online Kütüphane - <a asp-area="" asp-controller="Home" asp-action="Privacy">İletişim</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>