Book-Rental-MVC/Models/KitapTuru.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Book_Rental_MVC.Models
{
    public class KitapTuru
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Kitap Türü Adı boş bırakılamaz!")]
        [MaxLength(25)]
        [DisplayName("Kitap Türü Adı")]
        public string Ad { get; set; }
    }
}

Book-Rental-MVC/Controllers/KitapTuruController.cs
using Book_Rental_MVC.Models;
using Book_Rental_MVC.Models.Abstract;
using Book_Rental_MVC.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Book_Rental_MVC.Controllers
{
    [Authorize(Roles = UserRoles.Role_Admin)]
    public class KitapTuruController : Controller
    {
        private readonly IKitapTuruRepository _repository;
        public KitapTuruController(IKitapTuruRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            List<KitapTuru> kitapTuruList = _repository.GetAll().ToList();
            return View(kitapTuruList);
        }
         
        public IActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Ekle(KitapTuru model)
        {
            return Kaydet(model, false); // Ekleme işlemi
        }

        public IActionResult Guncelle(int? id)
        {
            return ContextBulVeDon(id);
        }

        [HttpPost]
        public IActionResult Guncelle(KitapTuru model)
        {
            return Kaydet(model, true); // Güncelleme işlemi
        }

        public IActionResult Sil(int? id)
        {
            return ContextBulVeDon(id);
        }

        [HttpPost, ActionName("Sil")]
        public IActionResult SilPost(int? id)
        {
            KitapTuru? kitapTuru = _repository.Get(i => i.Id == id);

            if (kitapTuru == null)
            {
                TempData["ErrorMessage"] = "Silmek istediğiniz kayıt bulunamadı!";
                return NotFound();
            }

            _repository.Sil(kitapTuru);
            _repository.Kaydet();
            TempData["SuccessMessage"] = "Kitap türü başarıyla silindi!";

            return RedirectToAction("Index");
        }

        private IActionResult ContextBulVeDon(int? id)
        {
            if (id == null)
                return NotFound();

            KitapTuru? kitapTuruVt = _repository.Get(i => i.Id == id); // idye ait kaydi getir

            if (kitapTuruVt == null)
                return NotFound();

            return View(kitapTuruVt);
        }

        private IActionResult Kaydet(KitapTuru model, bool isUpdate)
        {
            if (ModelState.IsValid)
            {
                if (isUpdate)
                {
                    _repository.Guncelle(model);
                    TempData["SuccessMessage"] = "Kitap türü başarıyla güncellendi!";
                }
                else
                {
                    _repository.Ekle(model);
                    TempData["SuccessMessage"] = "Kitap türü başarıyla eklendi!";
                }

                _repository.Kaydet();
                return RedirectToAction("Index");
            }

            TempData["ErrorMessage"] = "İşlem sırasında bir hata oluştu!";
            return View(model);
        }
    }
}

Book-Rental-MVC/Views/KitapTuru/Ekle.cshtml
@model KitapTuru


<form method="post">
    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-primary">Kitap Türü Ekle</h2>
            <hr />
        </div>

        <div class="mb-3">
            <label asp-for="Ad" class="p-0"></label>
            <input asp-for="Ad" class="form-control"/>
            <span asp-validation-for="Ad" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-lg btn-primary">Kitap Türü Ekle</button>

        <a asp-controller="KitapTuru" asp-action="Index" class="btn btn-lg btn-primary">Geri Dön</a>
    </div>
</form>

Book-Rental-MVC/Views/KitapTuru/Guncelle.cshtml
@model KitapTuru


<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-primary">Kitap Türü Güncelle</h2>
            <hr />
        </div>

        <div class="mb-3">
            <label asp-for="Ad" class="p-0"></label>
            <input asp-for="Ad" class="form-control" />
            <span asp-validation-for="Ad" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-lg btn-primary">Kitap Türü Güncelle</button>

        <a asp-controller="KitapTuru" asp-action="Index" class="btn btn-lg btn-primary">Geri Dön</a>
    </div>
</form>

Book-Rental-MVC/Views/KitapTuru/Index.cshtml
@model List<KitapTuru>

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}

<div class="container">

    <div class="row pt-3 pb-4">
        <div>
            <h1>Kitap Türleri</h1>
        </div>
    </div>
    
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>Kitap Türü</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Ad</td>
                    <td>
                        <a asp-controller="KitapTuru" asp-action="Guncelle" asp-route-id="@item.Id" class="btn btn-info" type="button" style="width:250px">Güncelle</a>
                    </td>
                    <td>
                        <a asp-controller="KitapTuru" asp-action="Sil" asp-route-id="@item.Id" class="btn btn-danger" type="button" style="width:250px">Sil</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div class="row pt-3 pb-2">
        <div>
            <a asp-controller="KitapTuru" asp-action="Ekle" class="btn btn-lg btn-primary" type="button">Yeni Kitap Türü Oluştur</a>
        </div>
    </div>
</div>

Book-Rental-MVC/Views/KitapTuru/Sil.cshtml
@model KitapTuru


<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-primary">Kitap Türü Sil</h2>
            <hr />
        </div>

        <div class="mb-3">
            <label asp-for="Ad" class="p-0"></label>
            <input asp-for="Ad" disabled class="form-control" />
        </div>

        <button type="submit" class="btn btn-lg btn-primary">Kitap Türü Sil</button>

        <a asp-controller="KitapTuru" asp-action="Index" class="btn btn-lg btn-primary">Geri Dön</a>
    </div>
</form>