Book-Rental-MVC/Models/Kitap.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Book_Rental_MVC.Models
{
    public class Kitap
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string KitapAdi { get; set; }

        public string Tanim { get; set; }

        [Required]
        public string Yazar { get; set; }

        [Required]
        [Range(10, 5000)]
        public double Fiyat { get; set; }

        [ValidateNever]
        public int KitapTuruId { get; set; }

        [ForeignKey(nameof(KitapTuruId))]
        [ValidateNever]
        public KitapTuru KitapTuru { get; set; }

        [ValidateNever]
        public string ResimUrl { get; set; }
    }
}

Book-Rental-MVC/Controllers/KitapController.cs
using Book_Rental_MVC.Models;
using Book_Rental_MVC.Models.Abstract;
using Book_Rental_MVC.Models.Concrete;
using Book_Rental_MVC.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;

namespace Book_Rental_MVC.Controllers
{
    public class KitapController : Controller
    {
        private readonly IKitapRepository _repository;
        private readonly IKitapTuruRepository _kitapTuruRepository;
        public readonly IWebHostEnvironment _webHostEnvironment;
        public KitapController(IKitapRepository kitapRepository, IKitapTuruRepository kitapTuruRepository, IWebHostEnvironment webHostEnvironment)
        {
            _repository = kitapRepository;
            _kitapTuruRepository = kitapTuruRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        [Authorize(Roles = "Admin,Ogrenci")]
        public IActionResult Index()
        {
            List<Kitap> kitapList = _repository.GetAll(includeProps:"KitapTuru").ToList();
            return View(kitapList);
        }

        [Authorize(Roles = UserRoles.Role_Admin)]
        public IActionResult EkleGuncelle(int? id)
        {
            IEnumerable<SelectListItem> KitapTuruList = _kitapTuruRepository.GetAll()
                .Select(k => new SelectListItem { Text = k.Ad, Value = k.Id.ToString() });

            ViewBag.KitapTuruList = KitapTuruList;

            if (id == null || id == 0)
                return View();
            else
                return ContextBulVeDon(id);
        }

        [Authorize(Roles = UserRoles.Role_Admin)]
        [HttpPost]
        public IActionResult EkleGuncelle(Kitap model, IFormFile? file)
        {
            if(ModelState.IsValid) 
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                string kitapPath = Path.Combine(wwwRootPath, @"img");

                if (file != null)
                {
                    using (var fileStream = new FileStream(Path.Combine(kitapPath, file.FileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    model.ResimUrl = @"\img\" + file.FileName;
                }
              
                if (model.Id == 0)
                {
                    _repository.Ekle(model);
                    TempData["SuccessMessage"] = "Yeni Kitap Oluşturuldu";
                }
                else
                {
                    _repository.Guncelle(model);
                    TempData["SuccessMessage"] = "Yeni Güncelleme Başarılı";
                }
                _repository.Kaydet();
                return RedirectToAction("Index");
            }
            return View();
        }

        [Authorize(Roles = UserRoles.Role_Admin)]
        public IActionResult Sil(int? id)
        {
            return ContextBulVeDon(id);
        }

        [Authorize(Roles = UserRoles.Role_Admin)]
        [HttpPost, ActionName("Sil")]
        public IActionResult SilPost(int? id)
        {
            Kitap? kitap = _repository.Get(i => i.Id == id);

            if (kitap == null)
            {
                TempData["ErrorMessage"] = "Silmek istediğiniz kayıt bulunamadı!";
                return NotFound();
            }

            _repository.Sil(kitap);
            _repository.Kaydet();
            TempData["SuccessMessage"] = "Kitap başarıyla silindi!";

            return RedirectToAction("Index");
        }

        private IActionResult ContextBulVeDon(int? id)
        {
            if (id == null)
                return NotFound();

            Kitap? kitapVt = _repository.Get(i => i.Id == id); // idye ait kaydi getir

            if (kitapVt == null)
                return NotFound();

            return View(kitapVt);
        }
    }
}

Book-Rental-MVC/Views/Kitap/Ekle.cshtml
@model Kitap


<form method="post">
    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-primary">Kitap Ekle</h2>
            <hr />
        </div>

        <div class="mb-3">
            <label asp-for="KitapAdi" class="p-0"></label>
            <input asp-for="KitapAdi" class="form-control" />
            <span asp-validation-for="KitapAdi" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Tanim" class="p-0"></label>
            <input asp-for="Tanim" class="form-control" />
            <span asp-validation-for="Tanim" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Yazar" class="p-0"></label>
            <input asp-for="Yazar" class="form-control" />
            <span asp-validation-for="Yazar" class="text-danger"></span>
        </div> 
        <div class="mb-3">
            <label asp-for="Fiyat" class="p-0"></label>
            <input asp-for="Fiyat" class="form-control" />
            <span asp-validation-for="Fiyat" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-lg btn-primary">Kitap Ekle</button>

        <a asp-controller="Kitap" asp-action="Index" class="btn btn-lg btn-primary">Geri Dön</a>
    </div>
</form>

Book-Rental-MVC/Views/Kitap/EkleGuncelle.cshtml
@model Kitap


<form method="post" enctype="multipart/form-data">
    <input asp-for="ResimUrl" hidden />
    <div class="row">
        <div class="col-10">
                <div class="border p-3 mt-5">
                    <div class="row pb-3">
                        <h2 class="text-primary">@(Model == null ? "Kitap Ekle" : "Kitap Güncelle")</h2>
                        <hr />
                    </div>

                    <div class="mb-3">
                        <label asp-for="KitapAdi" class="p-0"></label>
                        <input asp-for="KitapAdi" class="form-control" />
                        <span asp-validation-for="KitapAdi" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="KitapTuruId" class="p-0"></label>
                        <select asp-for="KitapTuruId" asp-items="ViewBag.KitapTuruList" class="form-select">
                        </select>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Tanim" class="p-0"></label>
                        <input asp-for="Tanim" class="form-control" />
                        <span asp-validation-for="Tanim" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Yazar" class="p-0"></label>
                        <input asp-for="Yazar" class="form-control" />
                        <span asp-validation-for="Yazar" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Fiyat" class="p-0"></label>
                        <input asp-for="Fiyat" class="form-control" />
                        <span asp-validation-for="Fiyat" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="ResimUrl" class="p-0"></label>
                        <input type="file" name="file" class="form-control" />
                    </div>

                    @if (Model != null)
                    {
                        <button type="submit" class="btn btn-lg btn-primary">Kitap Güncelle</button>
                    }
                    else
                    {
                        <button type="submit" class="btn btn-lg btn-primary">Kitap Ekle</button>
                    }

                    <a asp-controller="Kitap" asp-action="Index" class="btn btn-lg btn-primary">Geri Dön</a>
                </div>
        </div>

        <div class="col-2">
            @if (Model != null)
            {
                <img src="@Model.ResimUrl" width="100%" style="border-radius:7px; border:1px solid #bbb9b9" />
            }
        </div>
    </div>

</form>
    

Book-Rental-MVC/Views/Kitap/Index.cshtml
@using Book_Rental_MVC.Utility
@model List<Kitap>

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}

<div class="container">

    <div class="row pt-3 pb-4">
        <div>
            <h1>Kitaplar</h1>
        </div>
    </div>
    
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Resim</th>
                <th>Kitap Adi</th>
                <th>Tanım</th>
                <th>Yazar</th>
                <th>Fiyat</th>
                <th>Kitap Türü</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td align="center" valign="middle"><img src="@item.ResimUrl" style="border-radius: 7px; border: 1px solid #bbb9b9;
                                                    max-width: 145px; max: 275px;" /></td>
                    <td>@item.KitapAdi</td>
                    <td>@item.Tanim</td>
                    <td>@item.Yazar</td>
                    <td>@item.Fiyat</td>
                    <td>@item.KitapTuru.Ad</td>

                    @if (User.IsInRole(UserRoles.Role_Admin))
                    {
                        <td>
                            <a asp-controller="Kitap" asp-action="EkleGuncelle" asp-route-id="@item.Id" class="btn btn-info" type="button">Kitap Güncelle</a>
                        </td>
                        <td>
                            <a asp-controller="Kitap" asp-action="Sil" asp-route-id="@item.Id" class="btn btn-danger" type="button">Kitap Sil</a>
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>

    @if(User.IsInRole(UserRoles.Role_Admin))
                        {
    <div class="row pt-3 pb-2">
        <div>
            <a asp-controller="Kitap" asp-action="EkleGuncelle" class="btn btn-lg btn-primary" type="button">Yeni Kitap Oluştur</a>
        </div>
    </div>
                        }
</div>

Book-Rental-MVC/Views/Kitap/Sil.cshtml
@model Kitap


<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-5">
        <div class="row pb-3">
            <h2 class="text-primary">Kitap Sil</h2>
            <hr />
        </div>

        <div class="mb-3">
            <label asp-for="KitapAdi" class="p-0"></label>
            <input asp-for="KitapAdi" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Tanim" class="p-0"></label>
            <input asp-for="Tanim" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Yazar" class="p-0"></label>
            <input asp-for="Yazar" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Fiyat" class="p-0"></label>
            <input asp-for="Fiyat" disabled class="form-control" />
        </div>

        <button type="submit" class="btn btn-lg btn-primary">Kitap Sil</button>

        <a asp-controller="Kitap" asp-action="Index" class="btn btn-lg btn-primary">Geri Dön</a>
    </div>
</form>